.TH NXPROXY 1
.SH NAME
nxproxy \- The proxy part of the NX server for thin-clients.
.SH SYNOPSIS
.B nxproxy
.I "[options]" host:port
.SH DESCRIPTION
.B NX Proxy
is the proxy part of the free NX server by NoMachine.
.PP
This manual page documents briefly 
.BR NX Proxy
.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.

.SH OPTIONS
.TP
.B \--help
Show all options

.SH FILES
None

.SH NOTES
NoMachine offers a commercial and a freeware version of this server.
The freeware is named "NX Free Edition" and limited to two users.
FreeNX does not have such lemitations
A client needs the unfree "NX Client" which can be downloaded from
http://www.nomachine.com/download.php to make use of FreeNX

.SH KONTACT
Informations can be found on http://freenx.berlios.de/.

.SH AUTHOR
This manual page was written by Per Hansen <spamhans@yahoo.de>,
for the Debian GNU/Linux system (but may be used by others).

#.SH SEE ALSO
#java(1)
